using MethodOverloadGenerator.Models;

namespace MethodOverloadGenerator.Generation;

/// <summary>
/// Wraps a list of generated method bodies inside the correct partial-class and
/// optional namespace declaration, producing a complete, ready-to-emit source file.
/// </summary>
internal sealed class PartialClassEmitter
{
    /// <param name="declaration">
    /// Structural properties of the containing class (namespace, name, access modifier, static).
    /// </param>
    /// <param name="methodBodies">
    /// Already-rendered method declarations to embed inside the class body.
    /// </param>
    /// <returns>A complete C# source file as a string.</returns>
    public string Emit(DeclarationContext declaration, IReadOnlyList<string> methodBodies)
    {
        var classModifiers = AccessKeyword(declaration.ClassAccessModifier)
                            + (declaration.IsStaticClass ? " static" : "")
                            + " partial class";

        var classBlock = $$"""
            {{classModifiers}} {{declaration.ClassName}}
            {
            {{Indent(string.Join("\n\n", methodBodies))}}
            }
            """;

        var body = declaration.Namespace is null
            ? classBlock
            : $$"""
                namespace {{declaration.Namespace}}
                {
                {{Indent(classBlock)}}
                }
                """;

        var usings = string.Join("\n", BuildUsings(declaration));

        return $$"""
            // <auto-generated/>
            #nullable enable

            {{usings}}

            {{body}}
            """;
    }

    // "System"/"System.Threading.Tasks" are a baseline because Rule4/Rule5's receiver overloads
    // unconditionally introduce Task<T>/ValueTask<T> even when the original method never used
    // them. "System.Runtime.CompilerServices" is needed for every generated overload's
    // [OverloadResolutionPriority] attribute. Everything else is copied verbatim from the
    // original file's own usings rather than computed from what the generated signatures
    // actually need — far cheaper, and an unused using is harmless where a missing one is a
    // compile error (e.g. a delegate parameter typed as an interface that is only in scope via
    // a using, not by namespace).
    private static readonly string[] BaselineUsings =
    [
        "using System;",
        "using System.Threading.Tasks;",
        "using System.Runtime.CompilerServices;",
    ];

    private static IReadOnlyList<string> BuildUsings(DeclarationContext declaration)
        =>
        [
            .. BaselineUsings,
            .. declaration.Usings.Where(u => !BaselineUsings.Contains(u)),
        ];

    private static string Indent(string text)
        => string.Join("\n", text.Split('\n').Select(line => line.Length == 0 ? line : "    " + line));

    private static string AccessKeyword(AccessModifier m) => m switch
    {
        AccessModifier.Public            => "public",
        AccessModifier.Internal          => "internal",
        AccessModifier.Protected         => "protected",
        AccessModifier.ProtectedInternal => "protected internal",
        AccessModifier.PrivateProtected  => "private protected",
        _                                => "private",
    };
}
