using Microsoft.CodeAnalysis;

namespace MethodOverloadGenerator.Emission;

// Internal mirror of the emitted RuleOverride enum.
// Integer values MUST stay in sync with the enum definition inside Source below.
internal enum RuleOverride { Default = 0, Enable = 1, Disable = 2 }

internal static class AttributeEmitter
{
    internal static void Emit(IncrementalGeneratorPostInitializationContext context)
        => context.AddSource(GeneratorConstants.AttributeHintName, Source);

    // Exposed so RoslynTestHelper can use the same source rather than maintaining a duplicate.
    internal static readonly string Source = $$"""
        // <auto-generated/>
        #nullable enable

        using System;

        namespace MethodOverloadGenerator
        {
            /// <summary>
            /// Controls whether a rule is enabled, disabled, or deferred to the project-level
            /// MSBuild default for this decorated element.
            /// </summary>
            public enum RuleOverride
            {
                /// <summary>Inherit from the project's MSBuild property, or from the built-in default (enabled) if the property is not set.</summary>
                Default = 0,
                /// <summary>Force this rule on for the decorated element, regardless of the project default.</summary>
                Enable  = 1,
                /// <summary>Force this rule off for the decorated element, regardless of the project default.</summary>
                Disable = 2,
            }

            /// <summary>
            /// Instructs MethodOverloadGenerator to emit convenience overloads for delegate parameters.
            /// Can be placed on a parameter, method/constructor, or class.
            /// </summary>
            /// <remarks>
            /// Each rule can be individually overridden via its parameter.
            /// <see cref="RuleOverride.Default"/> (the default for every parameter) defers to the
            /// project-level MSBuild property, which itself defaults to enabled when not set.
            /// </remarks>
            [AttributeUsage(
                AttributeTargets.Class |
                AttributeTargets.Method |
                AttributeTargets.Constructor |
                AttributeTargets.Parameter,
                AllowMultiple = false,
                Inherited     = false)]
            public sealed class {{GeneratorConstants.AttributeClassName}} : Attribute
            {
                public RuleOverride SyncOverloads              { get; }
                public RuleOverride ValueOverloads             { get; }
                public RuleOverride TrailingParameterOverloads { get; }
                public RuleOverride TaskReceiverOverloads      { get; }
                public RuleOverride CombinatorialOverloads     { get; }

                public {{GeneratorConstants.AttributeClassName}}(
                    RuleOverride syncOverloads              = RuleOverride.Default,
                    RuleOverride valueOverloads             = RuleOverride.Default,
                    RuleOverride trailingParameterOverloads = RuleOverride.Default,
                    RuleOverride taskReceiverOverloads      = RuleOverride.Default,
                    RuleOverride combinatorialOverloads     = RuleOverride.Default)
                {
                    SyncOverloads              = syncOverloads;
                    ValueOverloads             = valueOverloads;
                    TrailingParameterOverloads = trailingParameterOverloads;
                    TaskReceiverOverloads      = taskReceiverOverloads;
                    CombinatorialOverloads     = combinatorialOverloads;
                }
            }
        }
        """;
}
