using Microsoft.CodeAnalysis;

namespace MethodOverloadGenerator.Emission;

/// <summary>
/// Polyfills <see cref="System.Runtime.CompilerServices.OverloadResolutionPriorityAttribute"/>
/// (a .NET 9+ BCL type) for consumers targeting an older framework, so the generated overloads
/// can carry it regardless of the consuming project's target framework. Guarded by
/// <c>#if !NET9_0_OR_GREATER</c> so it silently steps aside when the real BCL type already
/// exists — the same pattern Microsoft documents for manually polyfilling this attribute.
/// </summary>
internal static class OverloadResolutionPriorityAttributeEmitter
{
    internal static void Emit(IncrementalGeneratorPostInitializationContext context)
        => context.AddSource(GeneratorConstants.OverloadResolutionPriorityHintName, Source);

    // Exposed so RoslynTestHelper can use the same source rather than maintaining a duplicate.
    internal static readonly string Source = """
        // <auto-generated/>
        #nullable enable

        #if !NET9_0_OR_GREATER
        namespace System.Runtime.CompilerServices
        {
            [AttributeUsage(AttributeTargets.Method | AttributeTargets.Constructor, AllowMultiple = false, Inherited = false)]
            internal sealed class OverloadResolutionPriorityAttribute : Attribute
            {
                public OverloadResolutionPriorityAttribute(int priority)
                {
                    Priority = priority;
                }

                public int Priority { get; }
            }
        }
        #endif
        """;
}
